version: '3'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend